### ISSUE TITLE
API rate limit hit during build of a dependent package

### ISSUE THREAD

**Issue by marcellourbani** [SAP/generator-easy-ui5#100]
My CI builds started failing today because:

- I added this as a devdependency
- post install is hitting github which has a 60 request per hour rate limit on unauthenticated PI calls (generators/app/postinstall.js)
```javascript
  const octokit = new Octokit({
    userAgent: "generator-easy-ui5",
  });

  const reqBranch = await octokit.repos.getBranch({
    owner: ghOrg,
    repo: repoName,
    branch,
  });
```

I fixed it removing it as a dependency, leaving this message for posterity

**Comment by petermuessig** [comment]
Hi @marcellourbani ,

big sorry for replying that late to your issue.

The API limit happens when using the Octokit API without a GitHub auth token. Unfortunately, the GitHub auth token cannot be easily used in the `postinstall.js`. One option I can see is to use the GitHub auth token from the NPM configuration, e.g.:

```
npm config set easy-ui5_ghAuthToken=XXX
```

This could be used to also ensure that a GitHub auth token is used in the `postinstall.js`. It would require a little extension to the generator. 

Best regards,
Peter

**Comment by marcellourbani** [comment]
Thanks @petermuessig 
I didn't know about npm config, thanks!
Might warrant a line in README

**Comment by petermuessig** [comment]
@marcellourbani - this only works for the usage of the generator but it is not yet considered for the postinstall.js. This needs to be added there.
