### ISSUE TITLE
Not able to deploy the ui5 project to SAP ABAP server

### ISSUE THREAD

**Issue by saketamraotkar13** [SAP/generator-easy-ui5#77]
We are develop the ui5 project using yomen generator (easy ui5) and trying to deploy the app using npm run deploy but it did not deploy the app and gives the error "Error: Operation Existing Transport Determination for BSP Container: Expected status code 200, actual status code 403".

After investigation we came to know that issue is at the line no. 80:
fnCallback(new Error(Operation Existing Transport Determination: Expected status code ${fsutil.HTTPSTAT.ok}, actual status code ${oResponse.statusCode}));
it is not passing the credentials and coming back with mentioned error.

Please help us to resolve the issue.

Regards
Saket A

I'm sorry to hear that easy-ui5 generated broken files. Please report this issue directly in the repository for the plugin that you used. You can find all plugins in the [UI5 Community organization](https://github.com/ui5-community/). 

Here are a few direct links to some plugins:
* [UI5 Project](https://github.com/ui5-community/generator-ui5-project)
* [UI5 Library](https://github.com/ui5-community/generator-ui5-library)
* [UI5 Control](https://github.com/ui5-community/generator-ui5-control)

**Comment by IObert** [comment]
Hi, 

I'm afraid this issue is *NOT* related to the easy-ui5 project (which is why I'll close this issue). 
The problem you are facing is most likely related to either the chances you made to the project or to this repository [ui5-nwabap-deployer](https://github.com/pfefferf/ui5-nwabap-deployer). Please double-check and open, if needed, an issue over there.

It might be also related the this template project [here](https://github.com/ui5-community/generator-ui5-project) but before you open an issue, I would like to ask you to confirm that the deployment works with an empty project.
